name: Run Nginx Docker Container
 
on:
  push:
    branches:
      - master
 
jobs:
  run-nginx:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull Nginx Docker image
        run: sudo docker pull nginx
 
      - name: Run Nginx Docker conter on port 8087
        run: sudo docker run -d -p 8087:80 nginx
